{
  config,
  lib,
  pkgs,
  ...
}:

# Standalone Home Manager on a machine we do not own root on.
#
# Logins land in whatever /etc/passwd says — on shared boxes that is often a
# network share, not the home this configuration manages. We cannot edit passwd,
# so activation drops a bootstrap in the login home that redirects into this one.

let
  bootstrap = pkgs.writeText "hm-bootstrap.sh" ''
    # Generated by Home Manager. Edits are overwritten on activation.

    # Fall through quietly if the managed home is not mounted, so a broken
    # mount does not lock us out of the machine.
    [ -d "${config.home.homeDirectory}" ] || return 0

    export HOME="${config.home.homeDirectory}"
    cd "$HOME"

    # PATH, XDG_DATA_DIRS, EDITOR — written by programs.bash below.
    [ -r "$HOME/.profile" ] && . "$HOME/.profile"

    # Interactive only: exec'ing a shell would break `ssh host cmd` and scp.
    case $- in
      *i*) [ -x "$HOME/.nix-profile/bin/zsh" ] && exec "$HOME/.nix-profile/bin/zsh" -l ;;
    esac
  '';

  sourceLine = ''[ -r "$HOME/.hm-bootstrap.sh" ] && . "$HOME/.hm-bootstrap.sh"'';
in
{
  targets.genericLinux.enable = true;

  # Without root we cannot chsh, so login leaves SHELL pointing at the passwd
  # shell. tmux picks default-shell from SHELL first, then getpwuid, so new
  # panes would come up as login bash. Anything else reading SHELL — editors
  # opening a terminal, `git`'s pager setup — was getting bash too.
  home.sessionVariables.SHELL = "${config.programs.zsh.package}/bin/zsh";

  # The first build still needs --extra-experimental-features on the command
  # line; this keeps it enabled for every invocation after that. Written
  # directly rather than via nix.settings, which would pull a second Nix into
  # the profile and risk clashing with a root-managed daemon.
  xdg.configFile."nix/nix.conf".text = ''
    experimental-features = nix-command flakes
  '';

  # Not the interactive shell, but it is what the login shell reads, and it is
  # what emits the ~/.profile the bootstrap sources.
  programs.bash.enable = true;

  # logind starts the systemd user manager before our bootstrap runs, so it
  # derives its unit search path from the passwd home and never sees the units
  # written here. Atuin works fine without the daemon; it is a latency
  # optimisation. daemon-fuzzy requires it, so drop back to plain fuzzy.
  programs.atuin = {
    daemon.enable = lib.mkForce false;
    settings = {
      daemon.enabled = lib.mkForce false;
      search_mode = lib.mkForce "fuzzy";
    };
  };

  home.activation.loginHomeBootstrap = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    loginHome=$(${pkgs.getent}/bin/getent passwd "$(id -un)" | cut -d: -f6)

    if [ -n "$loginHome" ] && [ "$loginHome" != "$HOME" ] && [ -d "$loginHome" ]; then
      run install -m 0644 ${bootstrap} "$loginHome/.hm-bootstrap.sh"

      # Append to whichever login file already exists — creating .bash_profile
      # where only .profile exists would stop bash reading .profile at all.
      rc=""
      for candidate in .bash_profile .bash_login .profile; do
        if [ -f "$loginHome/$candidate" ]; then
          rc="$loginHome/$candidate"
          break
        fi
      done
      [ -n "$rc" ] || rc="$loginHome/.profile"

      if ! grep -qF '.hm-bootstrap.sh' "$rc" 2>/dev/null; then
        run tee -a "$rc" >/dev/null <<<${lib.escapeShellArg sourceLine}
      fi
    fi
  '';
}
