{
  config,
  lib,
  pkgs,
  ...
}:

# Standalone Home Manager on a machine we do not own root on.
#
# Logins land in whatever /etc/passwd says — on shared boxes that is often a
# network share, not the home this configuration manages. We cannot edit passwd,
# so activation drops a bootstrap in the login home that redirects into this one.

let
  bootstrap = pkgs.writeText "hm-bootstrap.sh" ''
    # Generated by Home Manager. Edits are overwritten on activation.

    # Fall through quietly if the managed home is not mounted, so a broken
    # mount does not lock us out of the machine.
    [ -d "${config.home.homeDirectory}" ] || return 0

    export HOME="${config.home.homeDirectory}"
    cd "$HOME"

    # PATH, XDG_DATA_DIRS, EDITOR — written by programs.bash below.
    [ -r "$HOME/.profile" ] && . "$HOME/.profile"

    # Interactive only: exec'ing a shell would break `ssh host cmd` and scp.
    case $- in
      *i*) [ -x "$HOME/.nix-profile/bin/zsh" ] && exec "$HOME/.nix-profile/bin/zsh" -l ;;
    esac
  '';

  sourceLine = ''[ -r "$HOME/.hm-bootstrap.sh" ] && . "$HOME/.hm-bootstrap.sh"'';
in
{
  targets.genericLinux.enable = true;

  # Not the interactive shell, but it is what the login shell reads, and it is
  # what emits the ~/.profile the bootstrap sources.
  programs.bash.enable = true;

  home.activation.loginHomeBootstrap = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    loginHome=$(${pkgs.getent}/bin/getent passwd "$(id -un)" | cut -d: -f6)

    if [ -n "$loginHome" ] && [ "$loginHome" != "$HOME" ] && [ -d "$loginHome" ]; then
      run install -m 0644 ${bootstrap} "$loginHome/.hm-bootstrap.sh"

      # Append to whichever login file already exists — creating .bash_profile
      # where only .profile exists would stop bash reading .profile at all.
      rc=""
      for candidate in .bash_profile .bash_login .profile; do
        if [ -f "$loginHome/$candidate" ]; then
          rc="$loginHome/$candidate"
          break
        fi
      done
      [ -n "$rc" ] || rc="$loginHome/.profile"

      if ! grep -qF '.hm-bootstrap.sh' "$rc" 2>/dev/null; then
        run tee -a "$rc" >/dev/null <<<${lib.escapeShellArg sourceLine}
      fi
    fi
  '';
}
