set -s escape-time 0
set -g set-clipboard on
set -g default-shell "/home/fjara/.nix-profile/bin/zsh"
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set-hook -g after-new-session "rename-session '#{b:session_path}'"

set -g mouse on
bind -T copy-mode-vi WheelUpPane select-pane \; send-keys -X -N 3 scroll-up
bind -T copy-mode-vi WheelDownPane select-pane \; send-keys -X -N 3 scroll-down

set -g mode-keys vi
set -g renumber-windows on
set -g history-limit 50000

# alt + < or > for changing windows
bind -n M-. next-window
bind -n M-, previous-window

# Status line
set -g status-left ''
set -g window-status-format " #{window_name} "
set -g window-status-current-format "◀ #{window_name} ▶"
set -g window-status-separator " | "
set -g status-right '𝄋 #{session_name} 𝄋'
set -g status-style fg=color8,bg=default
set -g window-status-current-style fg=white
